name: 'Reply with Shot'

on: [push]

jobs:
  tweet:
    runs-on: ubuntu-20.04

    steps:
      - uses: snow-actions/tweet@v1.2.0
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: |
            Hi there, this is your screenshot. 
          media_paths: |
            Shot.png
        
          
      - run: echo ${{ steps.tweet.outputs.response }}
